apps/web/src/components/header.tsx, apps/web/src/components/search/date-range-picker.tsx, apps/web/src/components/search/expanded-search.tsx, apps/web/src/components/search/guest-selector.tsx, apps/web/src/components/search/location-input.tsx, apps/web/src/components/search/search-button.tsx, apps/web/src/components/signin-button.tsx
- Add Guest and Tenant links in Login dropdown (/auth/guest-signin, /auth/tenant-signin)
- Minor tweaks to ExpandedSearch layout for better mobile
=> feat(header): make header mobile-friendly, extract login button

apps/web/src/app/globals.css, apps/web/src/app/property-detail/page.tsx, apps/web/src/components/reservation-card/page.tsx, apps/web/src/components/ui/card.tsx
- minus date range picker
- minus number of guest
=> feat(reservation): base reservation card creation

apps/api/src/controllers/booking.controller.ts, apps/api/src/services/booking.service.ts, packages/schemas/src/booking.schema.ts
add new data at booking.schema validation
fix error on booking.service
=> add new data on schema

apps/api/src/services/email.service.ts, apps/api/src/services/token.service.ts, apps/web/src/app/(auth)/complete-profile/page.tsx, apps/web/src/app/(auth)/guest-signup/page.tsx, apps/web/src/app/layout.tsx, apps/web/src/components/auth/complete-profile-form.tsx, apps/web/src/components/auth/complete-profile.utils.ts, apps/web/src/components/auth/signin-form.tsx, apps/web/src/lib/auth-error.utils.ts, packages/schemas/src/user.schema.ts
- Refactor signup & complete-profile to use shared utilities
- Extract shared auth error extractor (auth-error.utils.ts)
- Add complete-profile utils for avatar validation and FormData
- Mount global Sonner Toaster in root layout for visible toasts Improve server-side authorize logging
=> feat(signup): improve signup flow and error handling

apps/api/src/controllers/room.controller.ts, apps/api/src/routers/room.router.ts, apps/api/src/services/room.service.ts, apps/web/src/app/dashboard/tenant/properties/[id]/rooms/page.tsx, apps/web/src/components/tenant/room-availability-calendar.tsx, apps/web/src/components/tenant/room-form.tsx, apps/web/src/components/tenant/room-list.tsx, apps/web/src/components/tenant/room-management.tsx, apps/web/src/hooks/useRoomAvailability.ts, apps/web/src/types/room.ts, packages/database/prisma/schema.prisma, packages/database/src/seed.ts, packages/schemas/src/room.schema.ts
**Room Availability Management:**
- Added new controller methods (`getRoomAvailability`, `blockRoomDates`, `unblockRoomDates`) in `room.controller.ts` to handle fetching, blocking, and unblocking room dates, with schema validation for each operation. [[1]](diffhunk://#diff-b545636d2bb957723fd2fa7097831fbcb8a84d255817eb5466286ea18a6c1522L2-R8) [[2]](diffhunk://#diff-b545636d2bb957723fd2fa7097831fbcb8a84d255817eb5466286ea18a6c1522R102-R158)
- Implemented corresponding service methods in `room.service.ts` to interact with the database for retrieving, blocking, and unblocking room dates, including formatting for frontend consistency. [[1]](diffhunk://#diff-76c3e1ad772919614f5620a4968c42b3f82bbee051c5936f17bbc1b5f8d3646fL3-R9) [[2]](diffhunk://#diff-76c3e1ad772919614f5620a4968c42b3f82bbee051c59 …
=> feat(rooms): add availability management and room description support

apps/api/src/controllers/room.controller.ts, apps/api/src/routers/room.router.ts, apps/api/src/services/room.service.ts, apps/web/src/components/tenant/price-adjustment-modal.tsx, apps/web/src/components/tenant/room-list.tsx, apps/web/src/hooks/usePriceAdjustments.ts, apps/web/src/types/room.ts
This pull request introduces a new "Price Adjustment" feature for rooms, allowing users to create, view, update, and delete price adjustment rules. The changes span backend API endpoints, service logic, frontend hooks, and UI components to support managing price adjustments for rooms.
**Backend API and Service Enhancements:**
* Added new controller methods in `room.controller.ts` for creating, retrieving, updating, and deleting price adjustments, and registered corresponding routes in `room.router.ts` 
* Implemented service methods in `room.service.ts` to handle price adjustment logic, including validation, database operations, and formatting of response data.
**Frontend Functionality and UI:**
* Added a custom React hook `usePriceAdjustments` for fetching and managing price adjustments …
=> feat(price-adjustments): add price adjustment CRUD and UI for room rate rules

apps/api/src/routers/property.route.ts, apps/web/src/app/dashboard/tenant/properties/new/page.tsx, apps/web/src/components/tenant/property-creation/property-creation-context.tsx, apps/web/src/components/tenant/property-creation/property-creation-wizard.tsx, apps/web/src/components/tenant/property-creation/steps/category-step-fixed.tsx, apps/web/src/components/tenant/property-creation/steps/category-step.tsx, apps/web/src/components/tenant/property-creation/steps/facilities-step.tsx, apps/web/src/components/tenant/property-creation/steps/photos-step.tsx, apps/web/src/components/tenant/property-creation/steps/review-step.tsx, apps/web/src/components/tenant/property-creation/steps/rooms-step.tsx, apps/web/src/hooks/usePropertyCreation.ts, packages/schemas/src/facility.schema.ts, packages/schemas/src/index.ts
**Backend Security Enhancements:**
* The property creation endpoint now requires authentication and role verification, ensuring only authorized users can create properties (`property.route.ts`).
**Frontend: Property Creation Wizard Implementation**
* Added a full-featured, multi-step property creation wizard UI, replacing the placeholder page and integrating steps for basic info, location, category selection (with default/custom/new), rooms, facilities, photos, and review (`dashboard/tenant/properties/new/page.tsx`, `property-creation-wizard.tsx`). 
**Category Selection Step:**
* Implemented a new `CategoryStep` component allowing users to select a default category, choose from custom categories, or create a new one, with live updates to form data (`steps/category-step.tsx`).
**Form State …
=> feat(property): property creation UI — wizard, steps, validation and API hook

apps/api/src/controllers/property.controller.ts, apps/api/src/routers/property.route.ts, apps/web/src/components/tenant/property-creation/property-creation-context.tsx, apps/web/src/components/tenant/property-creation/steps/photos-step.tsx, apps/web/src/components/tenant/property-creation/steps/review-step.tsx, apps/web/src/components/tenant/property-creation/steps/rooms-step.tsx, apps/web/src/hooks/usePropertyCreation.ts
**Backend/API Enhancements:**
* Added `FileService` to the `PropertyController` and updated the `createProperty` method to handle multipart form data, process uploaded property and room images, and associate them with the correct data structures before validation and storage.
**Frontend Data Model and Submission:**
* Refactored the property creation context and form data types to support image files for both property pictures and room images, including new types (`PictureFormData`, `RoomFormData`) and logic for building `FormData` for API submission.
**UI/UX Improvements for Image Upload:**
* Redesigned the property photos step to support image file selection, preview, and removal, including file size/type validation and dynamic previews of selected images.
=> feat(property-creation): handle multipart property create — file uploads & previews

apps/api/src/configs/midtrans.config.ts, apps/api/src/services/booking/booking.service.ts, apps/web/package.json, apps/web/src/app/booking/page.tsx, apps/web/src/app/properties/[slug]/components/BookingSidebar.tsx, apps/web/src/components/guest/file-dropzone.tsx, apps/web/src/components/properties/PropertyCard.tsx, apps/web/src/components/ui/radio-group.tsx, package-lock.json, packages/database/prisma/schema.prisma, packages/database/src/seed.ts
Midtrans(api): setup and configuration for `createBooking` using Payment Gateway method.
Removing USD currency from all `basePrice` component
=> feat: Midtrans setup and configuration and fix currency

apps/web/src/components/header.tsx, apps/web/src/components/home/featured-properties.tsx, apps/web/src/components/home/popular-destinations.tsx, apps/web/src/components/home/property-categories.tsx, apps/web/src/components/home/why-choose-us.tsx, apps/web/src/components/properties/FiltersBar.tsx, apps/web/src/components/properties/PropertyCard.tsx, apps/web/src/components/search/location-input.tsx, apps/web/src/components/user-menu.tsx
**UI consistency and layout improvements:**
* Standardized vertical padding for section components on the home page (`featured-properties.tsx`, `popular-destinations.tsx`, `property-categories.tsx`, `why-choose-us.tsx`) to use `py-8` for better visual consistency across desktop and mobile. 
**Property card and image display enhancements:**
* Changed property card aspect ratio from `16/9` to `4/3` and ensured images use the first available picture (`Pictures[0]?.imageUrl`), improving image presentation and consistency in both `PropertyCard` and `FeaturedProperties`. Also added truncation for long property names to prevent layout overflow.
* Added `py-0` to property card containers to standardize card padding. 
**Responsive and accessibility improvements:**
* Modified the header search …
=> refactor(web): ui polish for homepage and property listing (responsive tweaks)

apps/api/src/services/booking/booking.service.ts, apps/web/src/app/booking/page.tsx, apps/web/src/components/guest/my-bookings/booking-table-row.tsx
Updated BookingTableRow Component
- Conditional action buttons based on booking status
- Integrated payment timer for waiting payments
- Cancel/Upload proof functionality
- Enhanced status display with payment proof indicators
=> API Integration: Connected booking page to backend booking service

apps/api/src/controllers/booking.controller.ts, apps/api/src/services/booking/booking.service.ts, apps/api/src/services/booking/core/booking-management.service.ts, apps/web/src/app/dashboard/tenant/transactions/page.tsx, apps/web/src/components/guest/my-bookings/booking-table-row.tsx
- Add cancel booking functionality for `WAITING_PAYMENT` status without payment proof
- Implement reject payment proof to change status back to `WAITING_PAYMENT` for re-upload
- Prevent booking cancellation after payment proof is uploaded
- Add approve/reject payment proof API endpoints with tenant authorization
- Update frontend table row component with conditional actions based on booking status
- Enhance payment proof controller with transaction safety and audit trail
=> feat: enhance payment proof workflow with improved booking status transitions

apps/web/src/components/search/search-button.tsx, apps/web/src/components/user-menu.tsx
UI/UX
- SearchButton: dynamic styles with animated border, shadow, scale, and color transitions
- UserMenu: updated sign-in button focus/active states, modernized dropdown with blur, spacing, and clearer sections
Iconography & Structure
- Added new icons (`HiOutlineArrowRight`, `HiOutlineUsers`) and updated terminology ("Become a Host")
- Improved menu layout with flexbox, consistent padding, hover effects, and smoother transitions
Accessibility
- Enhanced focus-visible states for buttons and menu items for better keyboard and screen reader support
=> feat(ui): improve search button and user menu design & accessibility

apps/web/src/components/header.tsx, apps/web/src/components/search/date-range-picker.tsx, apps/web/src/components/search/expanded-search.tsx, apps/web/src/components/search/guest-counter.tsx, apps/web/src/components/search/guest-selector.tsx, apps/web/src/components/search/location-input.tsx, apps/web/src/components/search/search-button.tsx
- Improved styling of search bar, inputs, and buttons with modern transitions, shadows, and focus states
- Added animation for search button label ↔ icon transition
- Animated guest counter when incrementing or decrementing values
- Updated date formatting in search queries to yyyy-MM-dd for cleaner URLs
- Improved focus, outlines, and cursor indicators for better accessibility
=> feat(search, header): improve UI, animations, and date formatting

apps/api/src/repositories/property.repository.ts, apps/api/src/services/price-calculation.service.ts, apps/api/src/services/property-search.service.ts, apps/web/src/app/dashboard/page.tsx, apps/web/src/components/home/featured-properties.tsx, apps/web/src/components/properties/PropertyCard.tsx, apps/web/src/lib/date-utils.ts, packages/schemas/src/property.schema.ts
- Add price calculation logic and expose minimum prices in property search.
- Improve property search by normalizing dates and handling guest counts.
- Fix calendar date formatting (avoid UTC shift) so toggling room availability writes the inten
- The date formatting bug caused tenant clicks in the calendar UI to be recorded as the previous day in the DB (due to UTC conversion). The refactor guarantees the picked calendar date is what the API receives.
- Price calculation + search improvements allow the UI to show correct minimum prices and return more accurate availability results when date/guest filters are present.
=> feat(property/search): price calculation + search improvements; fix(date-utils) to preserve calendar dates

apps/web/src/app/dashboard/tenant/properties/page.tsx, apps/web/src/components/dashboard/dashboard-page-header.tsx, apps/web/src/components/profile/account-page-content.tsx, apps/web/src/components/tenant/categories/category-form-dialog.tsx, apps/web/src/components/tenant/categories/category-management.tsx, apps/web/src/components/tenant/room-management-stats.tsx, apps/web/src/components/tenant/room-management.tsx, apps/web/src/hooks/useCategories.ts
UI consistency
- Introduce DashboardPageHeader and use it across tenant properties, account settings, and category management to standardize page headers/layouts.
Category dialogs
- Replace separate create/edit logic with CategoryFormDialog for better reuse and maintainability.
Error handling
- Remove success/error toasts in category CRUD; throw errors instead to centralize feedback.
Cleanup
- Tidy memoization/formatting in RoomManagementStats.
- Simplify filter logic in RoomManagement.
- Remove unused/commented code in useCategories.ts.
=> feat(ui,categories): add reusable DashboardPageHeader; refactor category dialogs; simplify error handling

apps/web/src/components/tenant/edit-property-form.tsx, apps/web/src/components/tenant/edit-property-form/basic-info-card.tsx, apps/web/src/components/tenant/edit-property-form/images-card.tsx, apps/web/src/components/tenant/edit-property-form/location-card.tsx, apps/web/src/components/tenant/edit-property-form/types.ts, apps/web/src/components/ui/location-picker.tsx, apps/web/src/components/ui/location-search-input.tsx, apps/web/src/hooks/use-location-picker.ts, apps/web/src/hooks/useEditProperty.ts, apps/web/src/lib/google-places.service.ts, apps/web/src/lib/location.utils.ts
UI/UX
Unified loading/error states with clearer messaging and consistent visuals
Modernized layout with better spacing and more prominent action buttons
Improved BasicInfoCard, LocationCard, and ImagesCard with subtitles, labels, and contextual help
Forms & Data
- Removed maxGuests field from forms and types
- Added onFieldsChange callback to location picker for better integration
Images
- Redesigned image upload: previews, counts, clearer remove/main image controls
- Upload button is more prominent, supports only image files
Code Organization
- Cleaned and reorganized imports
- Centralized hooks and simplified dependencies
Accessibility & Visuals
- Improved colors, spacing, and button sizing for better readability and accessibility
=> refactor(ui): improve property editing experience for tenants

apps/web/src/components/guest/booking-transaction/booking-content.tsx, apps/web/src/components/guest/booking-transaction/booking-summary-card.tsx, apps/web/src/components/guest/booking-transaction/context/booking-context.tsx, apps/web/src/components/guest/booking-transaction/hooks/use-booking-creation.ts, apps/web/src/components/guest/booking-transaction/hooks/use-midtrans.ts, apps/web/src/components/guest/booking-transaction/lib/booking-helpers.ts, apps/web/src/components/guest/booking-transaction/lib/midtrans-loader.ts, apps/web/src/components/guest/booking-transaction/payment-method-step.tsx, apps/web/src/components/guest/booking-transaction/payment-type-step.tsx, apps/web/src/components/guest/booking-transaction/payment-upload-modal.tsx, apps/web/src/components/guest/booking-transaction/review-step.tsx, apps/web/src/components/guest/booking-transaction/types/booking.types.ts, packages/database/prisma/schema.prisma
- Introduced `BookingContext` to eliminate props drilling
- Separated UI components, business logic hooks, and utilities
- Created 11 focused files with single responsibilities
- Maintained all existing functionality with improved maintainability
=> refactor(booking): split monolithic page into modular components with context

apps/web/src/components/providers/google-maps-provider.tsx, apps/web/src/components/tenant/edit-property-form/location-card.tsx, apps/web/src/components/tenant/location-form-body.tsx, apps/web/src/components/tenant/property-creation/steps/location-step.tsx, apps/web/src/components/ui/location-picker.tsx, apps/web/src/components/ui/location-suggestion-list.tsx
**Google Maps Integration Refactor:**
* Added a new `GoogleMapsProvider` component to manage loading the Google Maps API and provide loading/error state via context.
* Updated the `LocationPicker` component to use the new provider for API loading, removed direct API key dependency, and added user-friendly loading and error states.
**Form Component Consolidation:**
* Created a new `LocationFormBody` component to encapsulate all location-related form fields and logic, including map selection, address input, and validation.
* Refactored `LocationCard` and `LocationStep` components to use `LocationFormBody`, removing redundant form field markup and map logic, resulting in cleaner and more maintainable code. 
**Minor UI Improvement:**
* Improved accessibility and user experience for location …
=> refactor(forms): centralize Google Maps integration and consolidate location form logic

apps/web/src/components/tenant/edit-property-form.tsx, apps/web/src/components/tenant/edit-property-form/images-card.tsx, apps/web/src/components/tenant/property-creation/steps/photos-step.tsx, apps/web/src/components/tenant/shared/image-upload-area.tsx, apps/web/src/hooks/useEditProperty.ts
- Centralizing upload logic into a shared ImageUploadArea component
- Removing redundant state/props and unused code
- Improving gallery display with consistent ordering and empty state handling
=> refactor(image-upload): unify image upload workflows in property forms

apps/web/src/app/dashboard/tenant/page.tsx, apps/web/src/components/tenant/breadcrumb.tsx, apps/web/src/components/tenant/categories/category-selector-custom-section.tsx, apps/web/src/components/tenant/categories/category-selector-default-section.tsx, apps/web/src/components/tenant/edit-property-form.tsx, apps/web/src/components/tenant/edit-property-form/category-card.tsx, apps/web/src/components/ui/property-card.tsx, apps/web/src/hooks/useCategorySelection.ts, apps/web/src/hooks/useEditProperty.ts
- Accessibility & UX: Refactored category selector for keyboard support, consistent icons, and better text sizing.
- Property editing: Linked category selection to property updates with real-time state handling.
- UI updates: Added a delete button to property cards.
- Navigation: Cleaned up breadcrumbs by hiding ID-like segments.
- Cleanup: Removed leftover debugging comment.
=> feat(dashboard): improve category selection, property editing, and UI consistency

apps/web/src/components/guest/booking-transaction/booking-payment-proof-upload.tsx, apps/web/src/components/guest/booking-transaction/booking-summary-card.tsx, apps/web/src/components/guest/booking-transaction/cancellation-dialog.tsx, apps/web/src/components/guest/booking-transaction/payment-method-step.tsx, apps/web/src/components/guest/booking-transaction/payment-type-step.tsx, apps/web/src/components/guest/booking-transaction/payment-upload-modal.tsx, apps/web/src/components/guest/booking-transaction/review-step.tsx
-Add typography hierarchy and define selected font type
=> feat(UI): add typography hierarchy and define selected font type
